### ISSUE TITLE
Bot crashes on startup

### ISSUE THREAD

**Issue by AgitationSkeleton** [TotallyMehis/ssdb#6]
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\ssdb-master\ssdb.py", line 15, in <module>
    import valve.source.master_server
  File "C:\Python311\Lib\site-packages\valve\source\master_server.py", line 13, in <module>
    from . import messages
  File "C:\Python311\Lib\site-packages\valve\source\messages.py", line 379, in <module>
    class Message(collections.Mapping):
                  ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'collections' has no attribute 'Mapping'
Press any key to continue . . .

**Comment by TotallyMehis** [comment]
Error is caused by python-valve and that module is no longer maintained. It needs to be replaced. (#5)

As a workaround, you can apply this manually: https://github.com/serverstf/python-valve/pull/87

OR

Downgrade your Python.

**Comment by TotallyMehis** [comment]
Should work now.
